openproject/modules/costs/config/routes.rb
#-- copyright
# OpenProject Costs Plugin
#
# Copyright (C) 2009 - 2014 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#++

OpenProject::Application.routes.draw do
  scope 'projects/:project_id', as: 'projects' do
    resources :cost_entries, controller: 'costlog', only: [:new, :create]

    resources :cost_objects, only: [:new, :create, :index] do
      post :update_labor_budget_item, on: :collection
      post :update_material_budget_item, on: :collection
    end

    resources :hourly_rates, only: [:show, :edit, :update] do
      post :set_rate, on: :member
    end
  end

  scope 'work_packages/:work_package_id', as: 'work_packages' do
    resources :cost_entries, controller: 'costlog', only: %i[new]
  end

  resources :cost_entries, controller: 'costlog', only: [:edit, :update, :destroy]

  resources :cost_objects, only: [:show, :update, :destroy, :edit] do
    get :copy, on: :member
  end

  resources :cost_types, only: [:index, :new, :edit, :update, :create, :destroy] do
    member do
      # TODO: check if this can be replaced with update method
      put :set_rate
      patch :restore
    end
  end

  # TODO: this is a duplicate from a route defined under project/:project_id, check whether we really want to do that
  resources :hourly_rates, only: [:edit, :update]
end

openproject/modules/costs/app/controllers/cost_types_controller.rb
#-- copyright
# OpenProject Costs Plugin
#
# Copyright (C) 2009 - 2014 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#++

class CostTypesController < ApplicationController
  # Allow only admins here
  before_action :require_admin
  before_action :find_cost_type, only: [:edit, :update, :set_rate, :destroy, :restore]
  layout 'admin'

  helper :sort
  include SortHelper
  helper :cost_types
  include CostTypesHelper

  def index
    sort_init 'name', 'asc'
    sort_columns = { 'name' => "#{CostType.table_name}.name",
                     'unit' => "#{CostType.table_name}.unit",
                     'unit_plural' => "#{CostType.table_name}.unit_plural" }
    sort_update sort_columns

    @cost_types = CostType.order(sort_clause)

    unless params[:clear_filter]
      @fixed_date = Date.parse(params[:fixed_date]) rescue Date.today
      @include_deleted = params[:include_deleted]
    else
      @fixed_date = Date.today
      @include_deleted = nil
    end

    render action: 'index', layout: !request.xhr?
  end

  def edit
    render action: 'edit', layout: !request.xhr?
  end

  def update
    @cost_type.attributes = permitted_params.cost_type

    if @cost_type.save
      flash[:notice] = t(:notice_successful_update)
      redirect_back_or_default(action: 'index')
    else
      render action: 'edit', layout: !request.xhr?
    end
  rescue ActiveRecord::StaleObjectError
    # Optimistic locking exception
    flash.now[:error] = t(:notice_locking_conflict)
  end

  def new
    @cost_type = CostType.new

    @cost_type.rates.build(valid_from: Date.today) if @cost_type.rates.empty?

    render action: 'edit', layout: !request.xhr?
  end

  def create
    @cost_type = CostType.new(permitted_params.cost_type)

    if @cost_type.save
      flash[:notice] = t(:notice_successful_update)
      redirect_back_or_default(action: 'index')
    else
      @cost_type.rates.build(valid_from: Date.today) if @cost_type.rates.empty?
      render action: 'edit', layout: !request.xhr?
    end
  rescue ActiveRecord::StaleObjectError
    # Optimistic locking exception
    flash.now[:error] = t(:notice_locking_conflict)
  end

  def destroy
    @cost_type.deleted_at = DateTime.now
    @cost_type.default = false

    if @cost_type.save
      flash[:notice] = t(:notice_successful_lock)

      redirect_back_or_default(action: 'index')
    end
  end

  def restore
    @cost_type.deleted_at = nil
    @cost_type.default = false

    if @cost_type.save
      flash[:notice] = t(:notice_successful_restore)

      redirect_back_or_default(action: 'index')
    end
  end

  def set_rate
    today = Date.today

    rate = @cost_type.rate_at(today)
    rate ||= CostRate.new.tap do |cr|
      cr.cost_type  = @cost_type
      cr.valid_from = today
    end

    rate.rate = clean_currency(params[:rate])
    if rate.save
      flash[:notice] = t(:notice_successful_update)
      redirect_to action: 'index'
    else
      # FIXME: Do some real error handling here
      flash[:error] = t(:notice_something_wrong)
      redirect_to action: 'index'
    end
  end

  private

  def find_cost_type
    @cost_type = CostType.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def default_breadcrumb
    if action_name == 'index'
      CostType.model_name.human(count: 2)
    else
      ActionController::Base.helpers.link_to(CostType.model_name.human(count: 2), cost_types_path)
    end
  end

  def show_local_breadcrumb
    true
  end
end

openproject/modules/costs/app/helpers/cost_types_helper.rb
#-- copyright
# OpenProject Costs Plugin
#
# Copyright (C) 2009 - 2014 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#++

module CostTypesHelper
  include CostlogHelper
end

openproject/modules/costs/app/views/cost_types/_list.html.erb
<%#-- copyright
OpenProject Costs Plugin

Copyright (C) 2009 - 2014 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
version 3.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

++#%>

<% cost_types = @cost_types.reject(&:deleted_at) -%>

<% if cost_types.empty? %>
  <%= no_results_box %>
<% else %>
  <div class="generic-table--container">
    <div class="generic-table--results-container">
      <table class="generic-table">
        <colgroup>
          <col highlight-col>
          <col highlight-col>
          <col highlight-col>
          <col highlight-col>
          <col highlight-col>
          <col highlight-col>
          <col>
        </colgroup>
        <thead>
          <tr>
            <%= sort_header_tag 'name', :caption => CostType.model_name.human %>
            <%= sort_header_tag 'unit', :caption => CostType.human_attribute_name(:unit) %>
            <%= sort_header_tag 'unit_plural', :caption => CostType.human_attribute_name(:unit_plural) %>
            <th>
              <div class="generic-table--sort-header-outer">
                <div class="generic-table--sort-header">
                  <span>
                    <%= CostType.human_attribute_name(:current_rate) %>
                  </span>
                </div>
              </div>
            </th>
            <th>
              <div class="generic-table--sort-header-outer">
                <div class="generic-table--sort-header">
                  <span>
                    <%= t(:caption_set_rate) %>
                  </span>
                </div>
              </div>
            </th>
            <th>
              <div class="generic-table--sort-header-outer">
                <div class="generic-table--sort-header">
                  <span>
                    <%= t(:caption_default) %>
                  </span>
                </div>
              </div>
            </th>
            <th><div class="generic-table--empty-header"></div></th>
          </tr>
        </thead>
        <tbody>
          <% cost_types.each do |cost_type| %>
          <tr>
            <%= content_tag :td, link_to(cost_type.name, {:controller => '/cost_types', :action => 'edit', :id => cost_type}) %>
            <%= content_tag :td, cost_type.unit %>
            <%= content_tag :td, cost_type.unit_plural %>
            <%= content_tag :td, to_currency_with_empty(cost_type.rate_at(@fixed_date)), :class => "currency", :id => "cost_type_#{cost_type.id}_rate"%>
            <td>
              <%= form_for cost_type, :url => { :controller => '/cost_types', :action => 'set_rate', :id => cost_type }, method: :put, html: { class: 'inline-label' }  do |f| %>
                <label class="hidden-for-sighted" for="<%= "rate_field_#{cost_type.id}" %>"><%= t(:caption_set_rate) %></label>
                <%= content_tag :input, '', :value => "", :name => :rate, :size => 7, :id => "rate_field_#{cost_type.id}" %>
                <span class="form-label">
                  <%= Setting.plugin_openproject_costs['costs_currency'] %>
                </span>
                <button type="submit"
                        class="button submit_cost_type">
                  <%= icon_wrapper('icon icon-save', I18n.t(:caption_save_rate)) %>
                </button>
              <% end %>
            </td>
            <%= content_tag :td, cost_type.is_default? ? icon_wrapper('icon icon-checkmark', I18n.t(:general_text_Yes)) : "" %>
            <td class="buttons">
              <%= form_for cost_type, url:    cost_type_path(cost_type),
                                      method: :delete,
                                      html:   { id:    "delete_cost_type_#{cost_type.id}",
                                                class: 'delete_cost_type',
                                                title: t(:button_delete) } do |f| %>
                <button type="submit"
                        class="button submit_cost_type">
                  <%= icon_wrapper('icon icon-locked', I18n.t(:button_lock)) %>
                </button>
              <% end %>
            </td>
          </tr>
          <tr style="display:none;" >
          </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
<%# Moved from assets since this is the only remaining confirmation JS from the old costs code %>
<%= nonced_javascript_tag  do %>
  function submitForm(event, el) {
    submitFormWithConfirmation(event, el, true);
  }

  function submitFormWithConfirmation(event, el, withConfirmation) {
    event.preventDefault();

    if (!withConfirmation || confirm(I18n.t("js.text_are_you_sure"))) {
      jQuery(el).parent().submit();
    }

    return false;
  }
<% end %>
<% end %>

openproject/modules/costs/app/views/cost_types/_list_deleted.html.erb
<%#-- copyright
OpenProject Costs Plugin

Copyright (C) 2009 - 2014 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
version 3.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

++#%>

<% cost_types = @cost_types.select(&:deleted_at) -%>

<% if cost_types.empty? %>
  <%= no_results_box %>
<% else %>
  <div class="generic-table--container">
    <div class="generic-table--results-container">
      <table class="generic-table locked_cost_types">
        <colgroup>
          <col highlight-col>
          <col highlight-col>
          <col highlight-col>
          <col highlight-col>
          <col highlight-col>
          <col>
        </colgroup>
        <thead>
          <tr>
            <%= sort_header_tag("name", :caption => CostType.model_name.human) %>
            <%= sort_header_tag("unit", :caption => CostType.human_attribute_name(:unit)) %>
            <%= sort_header_tag("unit_plural", :caption => CostType.human_attribute_name(:unit_plural)) %>
            <th>
              <div class="generic-table--sort-header-outer">
                <div class="generic-table--sort-header">
                  <span>
                    <%= CostType.human_attribute_name(:current_rate) %>
                  </span>
                </div>
              </div>
            </th>
            <th>
              <div class="generic-table--sort-header-outer">
                <div class="generic-table--sort-header">
                  <span>
                    <%= t(:caption_locked_on) %>
                  </span>
                </div>
              </div>
            </th>
            <th><div class="generic-table--empty-header"></div></th>
          </tr>
          </thead>
          <tbody>
            <% cost_types.each do |cost_type| %>
              <tr>
                <%= content_tag :td, cost_type.name %>
                <%= content_tag :td, cost_type.unit %>
                <%= content_tag :td, cost_type.unit_plural %>
                <%= content_tag :td, to_currency_with_empty(cost_type.rate_at(@fixed_date)), :class => "currency" %>
                <%= content_tag :td, cost_type.deleted_at.to_date %>
                <td class="buttons">
                  <%= form_for cost_type, url: restore_cost_type_path(cost_type),
                                          method: :patch,
                                          html: { id: "restore_cost_type_#{cost_type.id}",
                                                  class: 'restore_cost_type' } do |f| %>
                    <button type="submit"
                            class="button submit_cost_type">
                      <%= icon_wrapper('icon icon-unlocked', I18n.t(:button_unlock)) %>
                    </button>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

      </div>
    </div>
<% end %>

openproject/modules/costs/app/views/cost_types/_rate.html.erb
<%#-- copyright
OpenProject Costs Plugin

Copyright (C) 2009 - 2014 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
version 3.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

++#%>

<%-
  templated ||= false
  index ||= "INDEX"
  new_or_existing = rate.new_record? ? 'new' : 'existing'
  id_or_index = rate.new_record? ? index : rate.id
  prefix = "cost_type[#{new_or_existing}_rate_attributes][]"
  id_prefix = "cost_type_#{new_or_existing}_rate_attributes_#{id_or_index}"
  name_prefix = "cost_type[#{new_or_existing}_rate_attributes][#{id_or_index}]"
  classes ||= ""
  classes += " subform-row-template" if templated

  @rate = rate
  error_messages = error_messages_for 'rate'
-%>


<% unless error_messages.blank? %>
  <tr><td colspan="3"><%= error_messages %></td></tr>
<% end %>
<%= fields_for prefix, rate do |rate_form| %>
  <tr class="subform-row <%= classes %>" id="<%= id_prefix %>">
    <td>
      <label class="hidden-for-sighted" for="<%= "#{id_prefix}_valid_from" %>"><%= Rate.human_attribute_name(:valid_from) %></label>
      <%= rate_form.text_field :valid_from,
                               class: 'date costs-date-picker -augmented-calendar',
                               index: id_or_index,
                               required: true %>
    </td>
    <td class="currency">
      <span class="inline-label">
        <label class="hidden-for-sighted" for="<%= "#{id_prefix}_rate" %>"><%= Rate.model_name.human %></label>
        <%= rate_form.text_field :rate,
                                 size: 7,
                                 index: id_or_index,
                                 value: rate.rate ? rate.rate.round(2) : "",
                                 required: true %>
        <span class="form-label">
          <%= Setting.plugin_openproject_costs['costs_currency'] %>
        </span>
      </span>
    </td>
    <td class="buttons">
      <a href="#" class="delete-row-button no-decoration-on-hover">
        <%= op_icon('icon-context icon-delete', title: t(:button_delete)) %>
      </a>
    </td>
  </tr>
<% end %>

openproject/modules/costs/app/views/cost_types/edit.html.erb
<%#-- copyright
OpenProject Costs Plugin

Copyright (C) 2009 - 2014 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
version 3.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

++#%>

<%= render partial: 'shared/costs_header' %>

<% if(@cost_type.id) %>
  <% html_title  t(:label_cost_type_specific, id: @cost_type.id, name: @cost_type.name) %>
  <% local_assigns[:additional_breadcrumb] = @cost_type.name %>
<% else %>
  <% html_title l(:label_administration), t(:label_cost_type_plural) %>
  <% local_assigns[:additional_breadcrumb] = l(:label_new) + ' ' + I18n.t('activerecord.models.cost_type.one') %>
<% end %>


<%= toolbar title: CostType.model_name.human %>

<%= activate_angular_js do %>
<costs-subform item-count="<%= @cost_type.rates.length %>">
<%= labelled_tabular_form_for @cost_type do |f| %>
  <%= error_messages_for 'cost_type' %>
  <%= back_url_hidden_field_tag %>

  <div class="form--field -required">
    <%= f.text_field :name, required: true, container_class: '-wide' %>
  </div>
  <div class="form--field -required">
    <%= f.text_field :unit, required: true, container_class: '-middle' %>
  </div>
  <div class="form--field -required">
    <%= f.text_field :unit_plural, required: true, container_class: '-middle' %>
  </div>
  <div class="form--field">
    <%= f.check_box :default %>
  </div>

  <h3><%= t :caption_rate_history %></h3>
  <div class="generic-table--container">
    <div class="generic-table--results-container">
      <table class="generic-table">
        <colgroup>
          <col highlight-col>
          <col highlight-col>
          <col>
        </colgroup>
        <thead>
          <tr>
            <th>
              <div class="generic-table--sort-header-outer">
                <div class="generic-table--sort-header">
                  <span>
                    <%= Rate.human_attribute_name(:valid_from) %>
                  </span>
                </div>
              </div>
            </th>
            <th class="currency">
              <div class="generic-table--sort-header-outer">
                <div class="generic-table--sort-header">
                  <span>
                    <%= Rate.model_name.human %>
                  </span>
                </div>
              </div>
            </th>
            <th><div class="generic-table--empty-header"></div></th>
          </tr>
        </thead>
        <tbody id="rates_body" class="subform-container">
          <%= render partial: "rate", object: CostRate.new, locals: { templated: true } %>
          <% @cost_type.rates.sort do |a,b|
            case
            when !a.valid? && !b.valid?
              0
            when !a.valid?
              -1
            when !b.valid?
              1
            else
              b.valid_from <=> a.valid_from
            end
          end.each_with_index do |rate, index| %>
            <%= render partial: 'rate', object: rate, locals: {index: index} %>
          <%- end -%>
        </tbody>
      </table>

    </div>
  </div>
  <div class="wp-inline-create-button">
    <label class="hidden-for-sighted" for="add_rate_date" %>"><%= t(:description_date_for_new_rate) %></label>
    <a id="add_rate_date" href="#" class="add-row-button wp-inline-create--add-link" title="<%= t(:button_add_rate) %>">
      <%= op_icon('icon icon-add') %>
    </a>
    <%= styled_button_tag t(:button_save), class: '-with-icon icon-checkmark' %>
  </div>
<% end %>
</costs-subform>
<% end %>

openproject/modules/costs/app/views/cost_types/index.html.erb
<%#-- copyright
OpenProject Costs Plugin

Copyright (C) 2009 - 2014 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
version 3.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

++#%>

<%= render partial: 'shared/costs_header' %>

<% html_title l(:label_administration), t(:label_cost_type_plural) %>
<%= toolbar title: CostType.model_name.human(count: 2) do %>
  <li class="toolbar-item">
    <a href="<%= new_cost_type_path %>" aria-label="<%= t(:button_add_cost_type) %>" title="<%= t(:button_add_cost_type) %>" class="button -alt-highlight">
      <%= op_icon('button--icon icon-add') %>
      <span class="button--text"><%= CostType.model_name.human %></span>
    </a>
  </li>
<% end %>

<%= styled_form_tag(cost_types_path, { method: :get, id: 'query_form' }) do %>
  <fieldset id="filters" class="simple-filters--container">
    <legend><%= t(:label_filter_plural) %></legend>
    <ul class="simple-filters--filters">
      <li class="simple-filters--filter">
        <%= styled_label_tag :fixed_date, t(:label_fixed_date), class: 'simple-filters--filter-name' %>
        <div class='simple-filters--filter-value'>
          <%= styled_text_field_tag :fixed_date, @fixed_date, class: '-augmented-datepicker' %>
        </div>
      </li>
      <li class="simple-filters--filter">
        <%= styled_label_tag :include_deleted, t(:caption_show_locked), class: 'simple-filters--filter-name -small' %>
        <div class="simple-filters--filter-value">
          <%= styled_check_box_tag :include_deleted, "1", @include_deleted, autocomplete: "off" %>
        </div>
      </li>
      <li class="simple-filters--controls">
        <%= submit_tag t(:button_apply), class: 'button -highlight -small' %>
        <%= link_to t(:button_clear), cost_types_path, class: 'button -small -with-icon icon-undo' %>
      </li>
    </ul>
  </fieldset>
<% end %>

<div id="cost_type_flash_notice_outer" style="display:none">
<div class="flash notice" id="cost_type_flash_notice"><%= t(:notice_successful_update) %></div>
</div>
<%= render partial: 'list' %>

<% if @include_deleted %>
  <div class="cost-types--list-deleted">
    <h3><%= t(:label_locked_cost_types) %></h3>
    <%= render partial: 'list_deleted' %>
  </div>
<% end %>