openproject/modules/backlogs/config/routes.rb
#-- copyright
# OpenProject Backlogs Plugin
#
# Copyright (C)2013-2014 the OpenProject Foundation (OPF)
# Copyright (C)2011 Stephan Eckardt, Tim Felgentreff, Marnen Laibow-Koser, Sandro Munda
# Copyright (C)2010-2011 friflaj
# Copyright (C)2010 Maxime Guilbot, Andrew Vit, Joakim Kolsjö, ibussieres, Daniel Passos, Jason Vasquez, jpic, Emiliano Heyns
# Copyright (C)2009-2010 Mark Maglana
# Copyright (C)2009 Joe Heck, Nate Lowrie
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 3.
#
# OpenProject Backlogs is a derivative work based on ChiliProject Backlogs.
# The copyright follows:
# Copyright (C) 2010-2011 - Emiliano Heyns, Mark Maglana, friflaj
# Copyright (C) 2011 - Jens Ulferts, Gregor Schmidt - Finn GmbH - Berlin, Germany
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.rdoc for more details.
#++

OpenProject::Application.routes.draw do
  scope '', as: 'backlogs' do
    scope 'projects/:project_id', as: 'project' do
      resources :backlogs,         controller: :rb_master_backlogs,  only: :index

      resources :sprints,          controller: :rb_sprints,          only: [:show, :update] do
        resource :query,            controller: :rb_queries,          only: :show

        resource :taskboard,        controller: :rb_taskboards,       only: :show

        resource :wiki,             controller: :rb_wikis,            only: [:show, :edit]

        resource :burndown_chart,   controller: :rb_burndown_charts,  only: :show

        resources :impediments,      controller: :rb_impediments,      only: [:create, :update]

        resources :tasks,            controller: :rb_tasks,            only: [:create, :update]

        resources :export_card_configurations, controller: :rb_export_card_configurations, only: [:index, :show] do
          resources :stories,          controller: :rb_stories,          only: [:index]
        end

        resources :stories,          controller: :rb_stories,          only: [:create, :update]
      end

      resource :query, controller: :rb_queries, only: :show
    end
  end

  get 'projects/:project_id/versions/:id/edit' => 'version_settings#edit'
  post 'projects/:id/project_done_statuses' => 'projects#project_done_statuses'
  post 'projects/:id/rebuild_positions' => 'projects#rebuild_positions'
end

openproject/modules/backlogs/app/controllers/rb_master_backlogs_controller.rb
#-- copyright
# OpenProject Backlogs Plugin
#
# Copyright (C)2013-2014 the OpenProject Foundation (OPF)
# Copyright (C)2011 Stephan Eckardt, Tim Felgentreff, Marnen Laibow-Koser, Sandro Munda
# Copyright (C)2010-2011 friflaj
# Copyright (C)2010 Maxime Guilbot, Andrew Vit, Joakim Kolsjö, ibussieres, Daniel Passos, Jason Vasquez, jpic, Emiliano Heyns
# Copyright (C)2009-2010 Mark Maglana
# Copyright (C)2009 Joe Heck, Nate Lowrie
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 3.
#
# OpenProject Backlogs is a derivative work based on ChiliProject Backlogs.
# The copyright follows:
# Copyright (C) 2010-2011 - Emiliano Heyns, Mark Maglana, friflaj
# Copyright (C) 2011 - Jens Ulferts, Gregor Schmidt - Finn GmbH - Berlin, Germany
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.rdoc for more details.
#++

class RbMasterBacklogsController < RbApplicationController
  menu_item :backlogs

  before_action :set_export_card_config_meta

  def index
    @owner_backlogs = Backlog.owner_backlogs(@project)
    @sprint_backlogs = Backlog.sprint_backlogs(@project)

    @last_update = (@sprint_backlogs + @owner_backlogs).map(&:updated_on).compact.max
  end

  private

  def set_export_card_config_meta
    @export_card_config_meta = {
      count: ExportCardConfiguration.active.count,
      default: ExportCardConfiguration.default
    }
  end

  def default_breadcrumb
    l(:label_backlogs)
  end
end

openproject/modules/backlogs/app/helpers/rb_master_backlogs_helper.rb
#-- copyright
# OpenProject Backlogs Plugin
#
# Copyright (C)2013-2014 the OpenProject Foundation (OPF)
# Copyright (C)2011 Stephan Eckardt, Tim Felgentreff, Marnen Laibow-Koser, Sandro Munda
# Copyright (C)2010-2011 friflaj
# Copyright (C)2010 Maxime Guilbot, Andrew Vit, Joakim Kolsjö, ibussieres, Daniel Passos, Jason Vasquez, jpic, Emiliano Heyns
# Copyright (C)2009-2010 Mark Maglana
# Copyright (C)2009 Joe Heck, Nate Lowrie
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 3.
#
# OpenProject Backlogs is a derivative work based on ChiliProject Backlogs.
# The copyright follows:
# Copyright (C) 2010-2011 - Emiliano Heyns, Mark Maglana, friflaj
# Copyright (C) 2011 - Jens Ulferts, Gregor Schmidt - Finn GmbH - Berlin, Germany
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.rdoc for more details.
#++

module RbMasterBacklogsHelper
  include Redmine::I18n

  def render_backlog_menu(backlog)
    # associated javascript defined in taskboard.js
    content_tag(:div, class: 'menu') do
      [
        content_tag(:div, '', class: "menu-trigger icon-context icon-pulldown icon-small"),
        content_tag(:ul, class: 'items') do
          backlog_menu_items_for(backlog).map { |item|
            content_tag(:li, item, class: 'item')
          }.join.html_safe
        end
      ].join.html_safe
    end
  end

  def backlog_menu_items_for(backlog)
    items = common_backlog_menu_items_for(backlog)

    if backlog.sprint_backlog?
      items.merge!(sprint_backlog_menu_items_for(backlog))
    end

    menu = []
    [:new_story, :stories_tasks, :task_board, :burndown, :cards, :wiki, :configs, :properties].each do |key|
      menu << items[key] if items.keys.include?(key)
    end

    menu
  end

  def common_backlog_menu_items_for(backlog)
    items = {}

    items[:new_story] = content_tag(:a,
                                    l('backlogs.add_new_story'),
                                    href: '#',
                                    class: 'add_new_story')

    items[:stories_tasks] = link_to(l(:label_stories_tasks),
                                    controller: '/rb_queries',
                                    action: 'show',
                                    project_id: @project,
                                    sprint_id: backlog.sprint)

    if @export_card_config_meta[:count] > 0
      items[:configs] = export_export_cards_link(backlog)
    end

    if current_user.allowed_to?(:manage_versions, @project)
      items[:properties] = properties_link(backlog)
    end

    items
  end

  def export_export_cards_link(backlog)
    if @export_card_config_meta[:count] == 1
      link_to(l(:label_backlogs_export_card_export),
              controller: '/rb_export_card_configurations',
              action: 'show',
              project_id: @project,
              sprint_id: backlog.sprint,
              id: @export_card_config_meta[:default],
              format: :pdf)
    else
      export_modal_link(backlog)
    end
  end

  def properties_link(backlog)
    back_path = backlogs_project_backlogs_path(@project)

    version_path = edit_version_path(backlog.sprint, back_url: back_path)

    link_to(l(:'backlogs.properties'), version_path)
  end

  def export_modal_link(backlog, options = {})
    path = backlogs_project_sprint_export_card_configurations_path(@project.id, backlog.sprint.id)
    html_id = "modal_work_package_#{SecureRandom.hex(10)}"
    link_to(l(:label_backlogs_export_card_export), path, options.merge(id: html_id, :'data-modal' => ''))
  end

  def sprint_backlog_menu_items_for(backlog)
    items = {}

    items[:task_board] = link_to(l(:label_task_board),
                                 { controller: '/rb_taskboards',
                                   action: 'show',
                                   project_id: @project,
                                   sprint_id: backlog.sprint },
                                 class: 'show_task_board')


    if backlog.sprint.has_burndown?
      items[:burndown] = content_tag(:a,
                                     l('backlogs.show_burndown_chart'),
                                     href: '#',
                                     class: 'show_burndown_chart')
    end

    if @project.module_enabled? 'wiki'
      items[:wiki] = link_to(l(:label_wiki),
                             controller: '/rb_wikis',
                             action: 'edit',
                             project_id: @project,
                             sprint_id: backlog.sprint)
    end

    items
  end
end

openproject/modules/backlogs/app/views/rb_master_backlogs/_backlog.html.erb
<%#-- copyright
OpenProject Backlogs Plugin

Copyright (C)2013-2014 the OpenProject Foundation (OPF)
Copyright (C)2011 Stephan Eckardt, Tim Felgentreff, Marnen Laibow-Koser, Sandro Munda
Copyright (C)2010-2011 friflaj
Copyright (C)2010 Maxime Guilbot, Andrew Vit, Joakim Kolsjö, ibussieres, Daniel Passos, Jason Vasquez, jpic, Emiliano Heyns
Copyright (C)2009-2010 Mark Maglana
Copyright (C)2009 Joe Heck, Nate Lowrie

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License version 3.

OpenProject Backlogs is a derivative work based on ChiliProject Backlogs.
The copyright follows:
Copyright (C) 2010-2011 - Emiliano Heyns, Mark Maglana, friflaj
Copyright (C) 2011 - Jens Ulferts, Gregor Schmidt - Finn GmbH - Berlin, Germany

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<% folded = current_user.backlogs_preference(:versions_default_fold_state) == "closed" %>
<div class="backlog" id="backlog_<%= backlog.sprint.id %>">
  <div class="header">
    <% icon = folded ? 'icon-arrow-down1' : 'icon-arrow-up1' %>
    <div class="toggler <%= icon %> icon-small<%= ' closed' if folded %>"> </div>
    <%= render :partial => "rb_sprints/sprint", :object => backlog.sprint %>
    <div class="velocity"> </div>
    <%= render_backlog_menu backlog %>
  </div>
  <ul class="stories<%= ' closed' if folded %>">
    <% reset_cycle 'stories' %>
    <% backlog.stories.each_with_index do |story, index| %>
      <% higher_item = index == 0 ? nil :
                                    backlog.stories[index - 1] %>

      <%= render :partial => "rb_stories/story",
                 :locals => { :story => story,
                              :higher_item => higher_item } %>
    <% end %>
  </ul>
</div>

openproject/modules/backlogs/app/views/rb_master_backlogs/index.html.erb
<%#-- copyright
OpenProject Backlogs Plugin

Copyright (C)2013-2014 the OpenProject Foundation (OPF)
Copyright (C)2011 Stephan Eckardt, Tim Felgentreff, Marnen Laibow-Koser, Sandro Munda
Copyright (C)2010-2011 friflaj
Copyright (C)2010 Maxime Guilbot, Andrew Vit, Joakim Kolsjö, ibussieres, Daniel Passos, Jason Vasquez, jpic, Emiliano Heyns
Copyright (C)2009-2010 Mark Maglana
Copyright (C)2009 Joe Heck, Nate Lowrie

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License version 3.

OpenProject Backlogs is a derivative work based on ChiliProject Backlogs.
The copyright follows:
Copyright (C) 2010-2011 - Emiliano Heyns, Mark Maglana, friflaj
Copyright (C) 2011 - Jens Ulferts, Gregor Schmidt - Finn GmbH - Berlin, Germany

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<% content_for :header_tags do %>
  <%= render :partial => 'shared/backlogs_header' %>
  <%= stylesheet_link_tag 'backlogs/master_backlog.css' %>
<% end %>

<div class='contextual'></div>
<% html_title l(:label_backlogs) %>

<%= toolbar title: t(:label_backlogs) do %>
    <li class="toolbar-item">
      <%= link_to_if_authorized({ controller: '/versions', action: 'new', project_id: @project },
                                { class: 'button -alt-highlight',
                                  aria: { label: t(:label_version_new) },
                                  title: t(:label_version_new) }) do %>
          <%= op_icon('button--icon icon-add') %>
          <span class="button--text"><%= t('activerecord.models.version') %></span>
      <% end %>
    </li>
<% end %>

<% if (@owner_backlogs.empty? && @sprint_backlogs.empty?) %>
  <%= no_results_box action_url: new_project_version_path(@project),
                     display_action: authorize_for('versions', 'new'),
                     custom_title: t(:backlogs_empty_title),
                     custom_action_text: t(:backlogs_empty_action_text)

  %>
<% end %>

<div id="rb">
  <div id="backlogs_container" class="clearfix">
    <div id="owner_backlogs_container">
      <%= render :partial => 'backlog', :collection => @owner_backlogs %>
    </div>
    <div id="sprint_backlogs_container">
      <%= render :partial => 'backlog', :collection => @sprint_backlogs %>
    </div>
  </div>

  <div id="helpers">
    <%= render :partial => "rb_stories/helpers" %>
    <div id="last_updated"><%= date_string_with_milliseconds(@last_update, 0.001) %></div>
  </div>
</div>