openproject/config/routes.rb
      get '(/*state)' => 'work_packages#show', on: :member, as: ''
    end

    resources :activity, :activities, only: :index, controller: 'activities'

    resources :forums do
      member do
        get :confirm_destroy
        get :move
        post :move
      end
    end

    resources :categories, except: %i[index show], shallow: true

    resources :members, only: %i[index create update destroy], shallow: true do
      collection do
        get :paginate_users
        match :autocomplete_for_member, via: %i[get post]
        get :all_members
      end
    end

    resource :repository, controller: 'repositories', except: [:new] do
      # Destroy uses a get request to prompt the user before the actual DELETE request
      get :destroy_info
      get :committers
      post :committers
      get :graph
      get :revisions

      get '/statistics', action: :stats, as: 'stats'

      get '(/revisions/:rev)/diff.:format', action: :diff
      get '(/revisions/:rev)/diff(/*repo_path)',
          action: :diff,
          format: 'html',
          constraints: { rev: /[\w0-9\.\-_]+/, repo_path: /.*/ }

      get '(/revisions/:rev)/:format/*repo_path',
          action: :entry,
          format: /raw/,
          rev: /[\w0-9\.\-_]+/

      %w{diff annotate changes entry browse}.each do |action|
        get "(/revisions/:rev)/#{action}(/*repo_path)",
            format: 'html',
            action: action,
            constraints: { rev: /[\w0-9\.\-_]+/, repo_path: /.*/ },
            as: "#{action}_revision"
      end

      get '/revision(/:rev)', rev: /[\w0-9\.\-_]+/,
                              action: :revision,
                              as: 'show_revision'

      get '(/revisions/:rev)(/*repo_path)',
          action: :show,
          format: 'html',
          constraints: { rev: /[\w0-9\.\-_]+/, repo_path: /.*/ },
          as: 'show_revisions_path'
    end
  end

  resources :admin, controller: :admin, only: :index do
    collection do
      get :plugins
      get :info
      post :force_user_language
      post :test_email
    end
  end

  scope 'admin' do
    resource :announcements, only: %i[edit update]
    constraints(Enterprise) do
      resource :enterprise, only: %i[show create destroy]
    end
    resources :enumerations

    delete 'design/logo' => 'custom_styles#logo_delete', as: 'custom_style_logo_delete'
    delete 'design/favicon' => 'custom_styles#favicon_delete', as: 'custom_style_favicon_delete'
    delete 'design/touch_icon' => 'custom_styles#touch_icon_delete', as: 'custom_style_touch_icon_delete'
    get 'design/upsale' => 'custom_styles#upsale', as: 'custom_style_upsale'
    post 'design/colors' => 'custom_styles#update_colors', as: 'update_design_colors'
    resource :custom_style, only: %i[update show create], path: 'design'

    resources :attribute_help_texts, only: %i(index new create edit update destroy)

    resources :groups do
      member do
        get :autocomplete_for_user
        # this should be put into it's own resource
        match '/members' => 'groups#add_users', via: :post, as: 'members_of'
        match '/members/:user_id' => 'groups#remove_user', via: :delete, as: 'member_of'
        # this should be put into it's own resource
        match '/memberships/:membership_id' => 'groups#edit_membership', via: :put, as: 'membership_of'
        match '/memberships/:membership_id' => 'groups#destroy_membership', via: :delete
        match '/memberships' => 'groups#create_memberships', via: :post, as: 'memberships_of'
      end
    end

    resources :roles, except: %i[show] do
      collection do
        put '/' => 'roles#bulk_update'
        get :report
      end
    end

    resources :auth_sources, :ldap_auth_sources do
      member do
        get :test_connection
      end
    end

    resources :custom_actions, except: :show

    namespace :oauth do
      resources :applications
    end
  end

  # We should fix this crappy routing (split up and rename controller methods)
  get '/settings' => 'settings#index'
  scope 'settings', controller: 'settings' do
    match 'edit', action: 'edit', via: %i[get post]
    match 'plugin/:id', action: 'plugin', via: %i[get post]
  end

  # We should fix this crappy routing (split up and rename controller methods)
  get '/workflows' => 'workflows#index'
  scope 'workflows', controller: 'workflows' do
    match 'edit', action: 'edit', via: %i[get post]
    match 'copy', action: 'copy', via: %i[get post]
  end

  namespace :work_packages do
    match 'auto_complete' => 'auto_completes#index', via: %i[get post]
    resources :calendar, controller: 'calendars', only: [:index]
    resource :bulk, controller: 'bulk', only: %i[edit update destroy]
    # FIXME: this is kind of evil!! We need to remove this soonest and
    # cover the functionality. Route is being used in work-package-service.js:331
    get '/bulk' => 'bulk#destroy'
  end

  resources :work_packages, only: [:index] do
    get :column_data, on: :collection # TODO move to API

    # move bulk of wps
    get 'move/new' => 'work_packages/moves#new', on: :collection, as: 'new_move'
    post 'move' => 'work_packages/moves#create', on: :collection, as: 'move'
    # move individual wp
    resource :move, controller: 'work_packages/moves', only: %i[new create]

    # this duplicate mapping is required for the timelog_helper
    namespace :time_entries do
      resource :report, controller: 'reports'
    end
    resources :time_entries, controller: 'timelog'

    # states managed by client-side routing on work_package#index
    get 'details/*state' => 'work_packages#index', on: :collection, as: :details

    # states managed by client-side (angular) routing on work_package#show
    get '/' => 'work_packages#index', on: :collection, as: 'index'
    get '/create_new' => 'work_packages#index', on: :collection, as: 'new_split'
    get '/new' => 'work_packages#index', on: :collection, as: 'new', state: 'new'
    get '(/*state)' => 'work_packages#show', on: :member, as: ''
    get '/edit' => 'work_packages#show', on: :member, as: 'edit'
  end

  resources :versions, only: %i[show edit update destroy] do
    member do
      get :status_by
    end
  end

  namespace :time_entries do
    resource :report, controller: 'reports',
                      only: [:show]
  end

  resources :time_entries, controller: 'timelog'

  resources :activity, :activities, only: :index, controller: 'activities'

  resources :users do
    resources :memberships, controller: 'users/memberships', only: %i[update create destroy]

    member do
      match '/edit/:tab' => 'users#edit', via: :get, as: 'tab_edit'
      match '/change_status/:change_action' => 'users#change_status_info', via: :get, as: 'change_status_info'
      post :change_status
      post :resend_invitation
      get :deletion_info
    end
  end

  resources :forums, only: [] do
    resources :topics, controller: 'messages', except: [:index], shallow: true do
      member do
        get :quote
        post :reply, as: 'reply_to'
      end
    end
  end

  resources :news, only: %i[index destroy update edit show] do
    resources :comments, controller: 'news/comments', only: %i[create destroy], shallow: true
  end

  # redirect for backwards compatibility
  scope 'attachments',
        constraints: { id: /\d+/, filename: /[^\/]*/ },
        format: false do
    get '/download/:id/:filename',
        to: redirect("#{rails_relative_url_root}/attachments/%{id}/%{filename}")

    get '/download/:id',
        to: redirect("#{rails_relative_url_root}/attachments/%{id}")

    scope ':id' do
      get '(/:filename)',
          to: redirect("#{rails_relative_url_root}/api/v3/attachments/%{id}/content")

      delete '',
             to: redirect("#{rails_relative_url_root}/api/v3/attachments/%{id}")
    end
  end

  resource :help, controller: :help, only: [] do
    member do
      get :keyboard_shortcuts
      get :text_formatting
    end
  end

  scope controller: 'sys' do
    match '/sys/repo_auth', action: 'repo_auth', via: %i[get post]
    get '/sys/projects', action: 'projects'
    get '/sys/fetch_changesets', action: 'fetch_changesets'
    get '/sys/projects/:id/repository/update_storage', action: 'update_required_storage'
  end

  # alternate routes for the current user
  scope 'my' do
    match '/deletion_info' => 'users#deletion_info', via: :get, as: 'delete_my_account_info'
    match '/oauth/revoke_application/:application_id' => 'oauth/grants#revoke_application', via: :post, as: 'revoke_my_oauth_application'
  end

  mount MyPage::Engine, at: "/my/page"

  scope controller: 'my' do
    get '/my/password', action: 'password'
    post '/my/change_password', action: 'change_password'

    get '/my/account', action: 'account'
    get '/my/settings', action: 'settings'
    get '/my/mail_notifications', action: 'mail_notifications'

    patch '/my/account', action: 'update_account'
    patch '/my/settings', action: 'update_settings'
    patch '/my/mail_notifications', action: 'update_mail_notifications'

    post '/my/generate_rss_key', action: 'generate_rss_key'
    post '/my/generate_api_key', action: 'generate_api_key'
    get '/my/access_token', action: 'access_token'
  end

  scope controller: 'onboarding' do
    patch 'user_settings', action: 'user_settings'
  end

  get 'authentication' => 'authentication#index'

  resources :colors do
    member do
      get :confirm_destroy
      get :move
      post :move
    end
  end

  # This route should probably be removed, but it's used at least by one cuke and we don't
  # want to break it.
  # This route intentionally occurs after the admin/roles/new route, so that one takes
  # precedence when creating routes (possibly via helpers).
  get 'roles/new' => 'roles#new', as: 'deprecated_roles_new'

  get '/robots' => 'homescreen#robots', defaults: { format: :txt }

  root to: 'account#login'

  # Development route for styleguide
  if Rails.env.development?

openproject/app/models/attribute_help_text/work_package.rb
#-- copyright
# OpenProject is a project management system.
# Copyright (C) 2012-2018 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2017 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See docs/COPYRIGHT.rdoc for more details.
#++

class AttributeHelpText::WorkPackage < AttributeHelpText
  def self.available_attributes
    attributes = ::Type.translated_work_package_form_attributes

    # Start and finish dates are joined into a single field for non-milestones
    attributes.delete 'start_date'
    attributes.delete 'due_date'

    # Status and project are currently special attribute that we need to add
    attributes['status'] = WorkPackage.human_attribute_name 'status'
    attributes['project'] = WorkPackage.human_attribute_name 'project'

    attributes
  end

  validates_inclusion_of :attribute_name, in: ->(*) { available_attributes.keys }

  def attribute_scope
    'WorkPackage'
  end

  def type_caption
    I18n.t(:label_work_package)
  end

  def self.visible_condition(user)
    visible_cf_names = WorkPackageCustomField
                       .visible_by_user(user)
                       .pluck(:id)
                       .map { |id| "custom_field_#{id}" }

    where(attribute_name: visible_cf_names)
      .or(where.not("attribute_name LIKE 'custom_field_%'"))
  end
end

openproject/app/models/queries/work_packages.rb
#-- encoding: UTF-8

#-- copyright
# OpenProject is a project management system.
# Copyright (C) 2012-2018 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2017 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See docs/COPYRIGHT.rdoc for more details.
#++

module Queries::WorkPackages
  filters_module = Queries::WorkPackages::Filter
  register = Queries::Register

  register.filter Query, filters_module::AssignedToFilter
  register.filter Query, filters_module::AssigneeOrGroupFilter
  register.filter Query, filters_module::AttachmentContentFilter
  register.filter Query, filters_module::AttachmentFileNameFilter
  register.filter Query, filters_module::AuthorFilter
  register.filter Query, filters_module::CategoryFilter
  register.filter Query, filters_module::CreatedAtFilter
  register.filter Query, filters_module::CustomFieldFilter
  register.filter Query, filters_module::DoneRatioFilter
  register.filter Query, filters_module::DueDateFilter
  register.filter Query, filters_module::EstimatedHoursFilter
  register.filter Query, filters_module::GroupFilter
  register.filter Query, filters_module::IdFilter
  register.filter Query, filters_module::PriorityFilter
  register.filter Query, filters_module::ProjectFilter
  register.filter Query, filters_module::ResponsibleFilter
  register.filter Query, filters_module::RoleFilter
  register.filter Query, filters_module::StartDateFilter
  register.filter Query, filters_module::StatusFilter
  register.filter Query, filters_module::SubjectFilter
  register.filter Query, filters_module::SubprojectFilter
  register.filter Query, filters_module::TypeFilter
  register.filter Query, filters_module::UpdatedAtFilter
  register.filter Query, filters_module::VersionFilter
  register.filter Query, filters_module::WatcherFilter
  register.filter Query, filters_module::DatesIntervalFilter
  register.filter Query, filters_module::ParentFilter
  register.filter Query, filters_module::PrecedesFilter
  register.filter Query, filters_module::FollowsFilter
  register.filter Query, filters_module::RelatesFilter
  register.filter Query, filters_module::DuplicatesFilter
  register.filter Query, filters_module::DuplicatedFilter
  register.filter Query, filters_module::BlocksFilter
  register.filter Query, filters_module::BlockedFilter
  register.filter Query, filters_module::PartofFilter
  register.filter Query, filters_module::IncludesFilter
  register.filter Query, filters_module::RequiresFilter
  register.filter Query, filters_module::RequiredFilter
  register.filter Query, filters_module::DescriptionFilter
  register.filter Query, filters_module::SearchFilter
  register.filter Query, filters_module::CommentFilter
  register.filter Query, filters_module::SubjectOrIdFilter
  register.filter Query, filters_module::ManualSortFilter
  register.filter Query, filters_module::RelatableFilter
  register.filter Query, filters_module::AssigneeOrAuthorFilter
  register.filter Query, filters_module::DepartmentFilter

  columns_module = Queries::WorkPackages::Columns

  register.column Query, columns_module::PropertyColumn
  register.column Query, columns_module::CustomFieldColumn
  register.column Query, columns_module::RelationToTypeColumn
  register.column Query, columns_module::RelationOfTypeColumn
end

openproject/app/models/queries/work_packages/filter.rb
#-- encoding: UTF-8
#-- copyright
# OpenProject is a project management system.
# Copyright (C) 2012-2018 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2017 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See docs/COPYRIGHT.rdoc for more details.
#++

module Queries::WorkPackages::Filter
end

openproject/app/views/work_packages/bulk/destroy.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2018 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2017 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See docs/COPYRIGHT.rdoc for more details.

++#%>
<%= error_messages_for work_packages.first %>

<%= styled_form_tag work_packages_bulk_path, method: :delete, class: 'form danger-zone' do %>
  <% work_packages.each do |work_package| %>
    <%= hidden_field_tag 'ids[]', work_package.id %>
  <% end %>

  <section class="form--section">
    <h3 class="form--section-title">
      <%= l('work_package.destroy.title') %>
    </h3>

    <%= work_package_associations_to_address(associated) %>

    <p>
      <strong><%= l(:text_destroy_what_to_do) %></strong>
    </p>

    <%= fields_for :to_do do |f| %>
      <div class="form--field -trailing-label">
        <%= styled_label_tag :to_do_action_destroy, l(:text_destroy) %>
        <div class="form--field-container">
          <%= styled_radio_button_tag 'to_do[action]', 'destroy' %>
        </div>
      </div>
      <div class="form--field -trailing-label">
        <%=styled_label_tag 'to_do_action_nullify', l(:text_assign_to_project) %>
        <div class="form--field-container">
          <%= styled_radio_button_tag 'to_do[action]' , 'nullify' %>
        </div>
      </div>
      <div class="grid-block">
        <div class="grid-block small-3">
          <div class="form--field -trailing-label">
            <%= styled_label_tag 'to_do_action_reassign', l(:text_reassign) %>
            <div class="form--field-container">
              <%= styled_radio_button_tag 'to_do[action]', 'reassign' %>
              <% csp_onclick('if(jQuery("#to_do_action_reassign").prop("checked")) { jQuery("#to_do_reassign_to_id").focus(); }',
                             '#reassign') %>
            </div>
          </div>
        </div>
        <div class="grid-block">
          <div class="form--field">
            <div class="form--text-field-container -xslim">
              <%= styled_label_tag 'to_do_reassign_to_id', l(:text_reassign), class: 'form--label hidden-for-sighted' %>
              <%= f.text_field 'reassign_to_id', placeholder: WorkPackage.human_attribute_name(:id), value: params[:reassign_to_id], size: 6, onfocus: 'jQuery("#to_do_action_reassign").prop("checked", true);' %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <div class="danger-zone--verification">
      <%= styled_button_tag title: l(:button_delete), class: '-highlight' do
            concat content_tag :i, '', class: 'button--icon icon-delete'
            concat content_tag :span, l(:button_delete), class: 'button--text'
            end %>
      <%= link_to_function l(:button_cancel),
                           "history.back()",
                           title: l(:button_cancel),
                           class: 'button -with-icon icon-cancel'%>
  </section>

<% end %>

openproject/app/views/work_packages/bulk/edit.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2018 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2017 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See docs/COPYRIGHT.rdoc for more details.

++#%>

<% html_title l(:label_bulk_edit_selected_work_packages) %>

<% if @bulk_errors.present? %>
  <div class="notification-box -error">
    <a title="close" class="notification-box--close icon-context icon-close"></a>
    <div class="notification-box--content">
      <p><strong><%= t('work_packages.bulk.could_not_be_saved') %></strong></p>

      <ul>
      <% @bulk_errors.each do |wpid, messages| %>
        <li>
          <%= link_to "##{wpid}", work_package_path(wpid) %>:
          <%= safe_join messages, ', ' %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

<h2><%= l(:label_bulk_edit_selected_work_packages) %></h2>
<ul>
  <% @work_packages.each do |wp| %>
    <li>
      <%= link_to(h("#{wp.type} ##{wp.id}"), work_package_path(wp)) %>:
      <%= wp.subject %>
    </li>
  <% end %>
</ul>

<%= styled_form_tag(url_for(controller: '/work_packages/bulk', action: :update),
             method: :put, class: '-wide-labels') do %>
  <% @work_packages.each do |wp| %>
    <%= hidden_field_tag 'ids[]', wp.id %>
  <% end %>
  <%= back_url_hidden_field_tag %>
  <section class="form--section">
    <fieldset class="form--fieldset">
      <legend class="form--fieldset-legend"><%= l(:label_change_properties) %></legend>
      <div class="grid-block">
        <div class="grid-content medium-6">
          <div class="form--field">
            <label class="form--label" for="work_package_type_id"><%= WorkPackage.human_attribute_name(:type) %></label>
            <div class="form--field-container">
              <%= styled_select_tag('work_package[type_id]', "<option value=\"\">#{l(:label_no_change_option)}</option>".html_safe + options_from_collection_for_select(@types, :id, :name)) %>
            </div>
          </div>
          <% if @available_statuses.any? %>
            <div class="form--field">
              <label class="form--label" for='status_id'><%= WorkPackage.human_attribute_name(:status) %></label>
              <div class="form--field-container">
                <%= styled_select_tag('work_package[status_id]', "<option value=\"\">#{l(:label_no_change_option)}</option>".html_safe + options_from_collection_for_select(@available_statuses, :id, :name)) %>
              </div>
            </div>
          <% else %>
            <div class="form--field">
              <label class="form--label" for='status_id'><%= WorkPackage.human_attribute_name(:status) %></label>
              <div class="form--field-container">
                <%= t('work_packages.move.no_common_statuses_exists') %>
              </div>
            </div>
          <% end %>
          <div class="form--field">
            <label class="form--label" for='work_package_priority_id'><%= WorkPackage.human_attribute_name(:priority) %></label>
            <div class="form--field-container">
              <%= styled_select_tag('work_package[priority_id]', "<option value=\"\">#{l(:label_no_change_option)}</option>".html_safe + options_from_collection_for_select(IssuePriority.active, :id, :name)) %>
            </div>
          </div>
          <div class="form--field">
            <label class="form--label" for='work_package_assigned_to_id'><%= WorkPackage.human_attribute_name(:assigned_to) %></label>
            <div class="form--field-container">
              <%= styled_select_tag('work_package[assigned_to_id]', content_tag('option', l(:label_no_change_option), value: '') +
                                     content_tag('option', l(:label_nobody), value: 'none') +
                                     options_from_collection_for_select(@assignables, :id, :name)) %>
            </div>
          </div>
          <div class="form--field">
            <label class="form--label" for='work_package_responsible_id'><%= WorkPackage.human_attribute_name(:responsible) %></label>
            <div class="form--field-container">
              <%= styled_select_tag('work_package[responsible_id]', content_tag('option', l(:label_no_change_option), value: '') +
                                     content_tag('option', l(:label_nobody), value: 'none') +
                                     options_from_collection_for_select(@responsibles, :id, :name)) %>
            </div>
          </div>
          <% if @project %>
            <div class="form--field">
              <label class="form--label" for='category_id'><%= WorkPackage.human_attribute_name(:category) %></label>
              <div class="form--field-container">
                <%= styled_select_tag('work_package[category_id]', content_tag('option', l(:label_no_change_option), value: '') +
                                    content_tag('option', l(:label_none), value: 'none') +
                                    options_from_collection_for_select(@project.categories, :id, :name)) %>
              </div>
            </div>
          <% end %>
          <% #TODO: allow editing versions when multiple projects %>
          <% if @project %>
            <div class="form--field">
              <label class="form--label" for='work_package_fixed_version_id'><%= WorkPackage.human_attribute_name(:fixed_version) %></label>
              <div class="form--field-container">
                <%= styled_select_tag('work_package[fixed_version_id]', content_tag('option', l(:label_no_change_option), value: '') +
                                       content_tag('option', l(:label_none), value: 'none') +
                                       version_options_for_select(@project.shared_versions.with_status_open.sort)) %>
              </div>
            </div>
          <% end %>
          <% @custom_fields.each do |custom_field| %>
            <div class="form--field">
              <%= blank_custom_field_label_tag('work_package', custom_field) %>
              <div class="form--field-container">
                <%= custom_field_tag_for_bulk_edit('work_package', custom_field, @project) %>
              </div>
            </div>
          <% end %>
          <%= call_hook(:view_work_packages_bulk_edit_details_bottom, { work_packages: @work_packages }) %>
        </div>
        <div class="grid-content medium-6">
          <% if @project && User.current.allowed_to?(:manage_subtasks, @project) %>
            <div class="form--field">
              <label class="form--label" for='work_package_parent_id'><%= WorkPackage.human_attribute_name(:parent) %></label>
              <div class="form--field-container">
                <%= styled_text_field_tag 'work_package[parent_id]', '', size: 10 %>
              </div>
            </div>
            <div id="parent_work_package_candidates" class="autocomplete"></div>
          <% end %>
          <div class="form--field">
            <label class="form--label" for='work_package_start_date'><%= WorkPackage.human_attribute_name(:start_date) %></label>
            <div class="form--field-container">
              <%= styled_text_field_tag 'work_package[start_date]', '', size: 10, class: '-augmented-datepicker' %>
            </div>
          </div>
          <div class="form--field">
            <label class="form--label" for='work_package_due_date'><%= WorkPackage.human_attribute_name(:due_date) %></label>
            <div class="form--field-container">
              <%= styled_text_field_tag 'work_package[due_date]', '', size: 10, class: '-augmented-datepicker' %>
            </div>
          </div>
          <% if WorkPackage.use_field_for_done_ratio? %>
            <div class="form--field">
              <label class="form--label" for='work_package_done_ratio'><%= WorkPackage.human_attribute_name(:done_ratio) %></label>
              <div class="form--field-container">
                <%= styled_select_tag 'work_package[done_ratio]', options_for_select([[l(:label_no_change_option), '']] + (0..10).to_a.collect {|r| ["#{r*10} %", r*10] }) %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </fieldset>
    <fieldset class="form--fieldset">
      <legend class="form--fieldset-legend"><%= Journal.human_attribute_name(:notes) %></legend>
      <%= label_tag 'notes', Journal.human_attribute_name(:notes), class: 'hidden-for-sighted' %>
      <%= styled_text_area_tag 'notes', @notes, class: 'wiki-edit', with_text_formatting: true %>
      <p><%= send_notification_option %></p>
    </fieldset>
  </section>
  <p><%= styled_button_tag l(:button_submit), class: '-highlight -with-icon icon-checkmark' %></p>
<% end %>